// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1:string):Promise<boolean>;

export function HandleFilePaths_ClearThumbnailsCache():Promise<void>;

export function HandleFilePaths_CompleteOperation(arg1:Array<string>):Promise<string>;

export function HandleFilePaths_GetPredefinedIcons():Promise<Record<string, string>>;

export function HandleFilePaths_GetThumbnails(arg1:Array<string>):Promise<void>;

export function HandleFilePaths_MarkFileOperate(arg1:string):Promise<void>;

export function HandleFilePaths_MarkFileOperation(arg1:string):Promise<string>;

export function HandleFilePaths_OperateWithClipboard(arg1:Array<string>):Promise<string>;

export function HideWindow():Promise<void>;
