// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFileExists(arg1) {
  return window['go']['main']['App']['CheckFileExists'](arg1);
}

export function HandleFilePaths_ClearThumbnailsCache() {
  return window['go']['main']['App']['HandleFilePaths_ClearThumbnailsCache']();
}

export function HandleFilePaths_CompleteOperation(arg1) {
  return window['go']['main']['App']['HandleFilePaths_CompleteOperation'](arg1);
}

export function HandleFilePaths_GetThumbnails(arg1) {
  return window['go']['main']['App']['HandleFilePaths_GetThumbnails'](arg1);
}

export function HandleFilePaths_MarkFileOperate(arg1) {
  return window['go']['main']['App']['HandleFilePaths_MarkFileOperate'](arg1);
}

export function HandleFilePaths_MarkFileOperation(arg1) {
  return window['go']['main']['App']['HandleFilePaths_MarkFileOperation'](arg1);
}

export function HandleFilePaths_OperateWithClipboard(arg1) {
  return window['go']['main']['App']['HandleFilePaths_OperateWithClipboard'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}
